### ISSUE TITLE
Hello Again Sir..:D

### ISSUE THREAD

**Issue by joielechong** [tronium/SupervisoryTerminal#1]
Hello Sir, 

It's been so long that we haven't met Sir. I'm Juan Rio Sipayung, I think you didn't remember me now.

How are you now Sir? 

May God bless you.

Sincerely yours ex-student,

Juan.

**Comment by tronium** [comment]
Hi Juan. I still remember you... the skinny techie guy :) Where are you now? Still doing freelancing or already had a company on your own?
Btw, I was surprised that I thought you found a bug in the firmware of this project :) Shall we move to another chat channel? Do you have a hangout account? I hope you don't mind I close this 'issue'.

**Comment by joielechong** [comment]
Still in Medan Sir. I'm currently still an employee guy Sir. But in the process of building a company, a baby step for it Sir :D.
Hardware stuff isn't my thing for now Sir. No hard feeling for closed issue Sir.


Here my email Sir: juansspy _at_ gmail _dot_ com.
